import turtle

def stairs(stairs_count, shape):
    for i in range(stairs_count):
        shape.forward(15)
        shape.left(90)
        shape.forward(15)
        shape.right(90)

circle = turtle.Turtle()
circle.shape('circle')
circle.color('blue', 'cyan')
circle.pensize(10)
circle.right(90)
circle.forward(50)
circle.left(90)
circle.begin_fill()
circle.circle(165)
circle.end_fill()

heart = turtle.Turtle()
heart.shape("turtle")
heart.color('red', 'pink')
heart.speed(10)
heart.pensize(6)
heart.begin_fill()
stairs(9,heart)
heart.left(90)
stairs(5,heart)
heart.left(90)
stairs(4,heart)
heart.right(90)
stairs(4,heart)
heart.left(90)
stairs(5,heart)
heart.left(90)
stairs(9,heart)
heart.end_fill()
turtle.exitonclick()